const global = {};

// functions

let toMixArray = (array) => {
	var currentIndex = array.length,
		temporaryValue, randomIndex;
	while (0 !== currentIndex) {
		randomIndex = Math.floor(Math.random() * currentIndex);
		currentIndex -= 1;
		temporaryValue = array[currentIndex];
		array[currentIndex] = array[randomIndex];
		array[randomIndex] = temporaryValue;
	}

	return array;
};

let toCompareTwoObjects = (obj1, obj2) => {
	let comparisonObj = {};
	if (Object.keys(obj1).length === 0 || Object.keys(obj2).length === 0) {
		return false;
	} else {
		for (let k in obj1) {
			comparisonObj[k] = (obj1[k] === obj2[k])
		}
	}

	return comparisonObj;
};

let toResultTest = (answerArray) => {
	let resultArr = [];

	for(let i=0; i<answerArray.length; i++) {
		let result = true;
		for(let k in answerArray[i]) {
			
			if(answerArray[i][k] === false) {
				 result = false
			}
		}
		resultArr[i] = result;
	}

	return resultArr;
};

global.toMixArray = toMixArray;
global.toCompareTwoObjects = toCompareTwoObjects;
global.toResultTest = toResultTest;

// vars

const levels = [{
		level: 0,
		name: 'zero',
		amount: 4,
		descr: 'Уровень 0: (Ноль) Вам предстоит пройти тест всего из 10 неправильных глаголов, которые будут сгенерированы из нулевой группы глаголов',
	},
	{
		level: 1,
		name: 'dummy',
		amount: 20,
		descr: 'Уровень 1: (Дурачок) Вам предстоит пройти тест из 20 неправильных глаголов, которые будут сгенерированы из нулевой группы глаголов',
	},
	{
		level: 2,
		name: 'schoolkid',
		amount: 30,
		descr: 'Уровень 2: (Школьник) Вам предстоит пройти тест из 30 неправильных глаголов, которые будут сгенерированы из нулевой группы глаголов',
	},
	{
		level: 3,
		name: 'middle',
		amount: 40,
		descr: 'Уровень 3: (Средний) Вам предстоит пройти тест из 40 неправильных глаголов, которые будут сгенерированы из нулевой и первой групп глаголов',
	},
	{
		level: 4,
		name: 'veteran',
		amount: 50,
		descr: 'Уровень 4: (Ветеран) Вам предстоит пройти тест из 50 неправильных глаголов, которые будут сгенерированы из нулевой, первой и второй групп глаголов',
	},
	{
		level: 5,
		name: 'expert',
		amount: 65,
		descr: 'Уровень 5: (Эксперт) Вам предстоит пройти тест из 65 неправильных глаголов, которые будут сгенерированы из нулевой, первой и второй групп глаголов',
	},
	{
		level: 6,
		name: 'God',
		amount: 80,
		descr: 'Уровень 6: (Божество) Вам предстоит пройти тест из 80 неправильных глаголов, которые будут сгенерированы из нулевой, первой и второй групп глаголов',
	},
]

const verbForms = [{
		id: 1,
		name: 'infinitive',
		var: 'infinitive'
	},
	{
		id: 2,
		name: 'past simple',
		var: 'pastSimple'
	},
	{
		id: 3,
		name: 'past participle',
		var: 'pastParticiple'
	}
];

const verbsList = [{
		id: 1,
		rus: 'пребывать, придерживаться чего-либо',
		infinitive: 'abide',
		pastSimple: 'abode',
		pastParticiple: 'abode',
		group: 1,
	},
	{
		id: 2,
		rus: 'возникать, подниматься',
		infinitive: 'arise',
		pastSimple: 'arose',
		pastParticiple: 'arisen',
		group: 1,
	},
	{
		id: 3,
		rus: 'будить, просыпаться',
		infinitive: 'awake',
		pastSimple: 'awoke',
		pastParticiple: 'awoken',
		group: 1,
	},
	{
		id: 4,
		rus: 'быть, являться',
		infinitive: 'be',
		pastSimple: 'was/were',
		pastParticiple: 'been',
		group: 1,
	},
	{
		id: 5,
		rus: 'рождать/рожать ',
		infinitive: 'bear',
		pastSimple: 'bore',
		pastParticiple: 'born',
		group: 1,
	},
	{
		id: 6,
		rus: 'становиться/делаться',
		infinitive: 'become',
		pastSimple: 'became',
		pastParticiple: 'become',
		group: 1,
	},
	{
		id: 7,
		rus: 'цепляться',
		infinitive: 'cling',
		pastSimple: 'clung',
		pastParticiple: 'clung',
		group: 1,
	},
	{
		id: 8,
		rus: 'случаться',
		infinitive: 'befall',
		pastSimple: 'befell',
		pastParticiple: 'befallen',
		group: 1,
	},
	{
		id: 9,
		rus: 'начинать(ся)',
		infinitive: 'begin',
		pastSimple: 'began',
		pastParticiple: 'begun',
		group: 1,
	},
	{
		id: 10,
		rus: 'вглядываться/замечать',
		infinitive: 'behold',
		pastSimple: 'beheld',
		pastParticiple: 'beheld',
		group: 1,
	},
	{
		id: 11,
		rus: 'гнуть(ся)/сгибать(ся)',
		infinitive: 'bend',
		pastSimple: 'bent',
		pastParticiple: 'bent',
		group: 1,
	},
	{
		id: 12,
		rus: 'умолять, упрашивать',
		infinitive: 'beseech',
		pastSimple: 'besought',
		pastParticiple: 'besought',
		group: 1,
	},
	{
		id: 13,
		rus: 'окружать/осаждать',
		infinitive: 'beset',
		pastSimple: 'beset',
		pastParticiple: 'beset',
		group: 1,
	},
	{
		id: 14,
		rus: 'держать пари',
		infinitive: 'bet',
		pastSimple: 'bet',
		pastParticiple: 'bet',
		group: 1,
	},
	{
		id: 15,
		rus: 'предлагать цену/велеть/просить',
		infinitive: 'bid',
		pastSimple: 'bid',
		pastParticiple: 'bid',
		group: 1,
	},
	{
		id: 16,
		rus: 'связывать',
		infinitive: 'bind',
		pastSimple: 'bound',
		pastParticiple: 'bound',
		group: 1,
	},
	{
		id: 17,
		rus: 'кусать(ся)',
		infinitive: 'bite',
		pastSimple: 'bit',
		pastParticiple: 'bitten',
		group: 1,
	},
	{
		id: 18,
		rus: 'кровоточить/опорожнять',
		infinitive: 'bleed',
		pastSimple: 'bled',
		pastParticiple: 'bled',
		group: 1,
	},
	{
		id: 19,
		rus: 'дуть',
		infinitive: 'blow',
		pastSimple: 'blew',
		pastParticiple: 'blown',
		group: 1,
	},
	{
		id: 20,
		rus: 'ломат/прерывать/разбивать',
		infinitive: 'break',
		pastSimple: 'broke',
		pastParticiple: 'broken',
		group: 1,
	},
	{
		id: 21,
		rus: 'порождать/разводить/выводить',
		infinitive: 'breed',
		pastSimple: 'bred',
		pastParticiple: 'bred',
		group: 1,
	},
	{
		id: 22,
		rus: 'приносить/приводить',
		infinitive: 'bring',
		pastSimple: 'brought',
		pastParticiple: 'brought',
		group: 1,
	},
	{
		id: 23,
		rus: 'вещать/распространять',
		infinitive: 'broadcast',
		pastSimple: 'broadcast',
		pastParticiple: 'broadcast',
		group: 1,
	},
	{
		id: 24,
		rus: 'строить/встраивать',
		infinitive: 'build',
		pastSimple: 'built',
		pastParticiple: 'built',
		group: 1,
	},
	{
		id: 25,
		rus: 'гореть/сжигать',
		infinitive: 'burn',
		pastSimple: 'burnt',
		pastParticiple: 'burnt',
		group: 1,
	},
	{
		id: 26,
		rus: 'взрывать(ся)',
		infinitive: 'burst',
		pastSimple: 'burst',
		pastParticiple: 'burst',
		group: 1,
	},
	{
		id: 27,
		rus: 'покупать',
		infinitive: 'buy',
		pastSimple: 'bought',
		pastParticiple: 'bought',
		group: 1,
	},
	{
		id: 28,
		rus: 'мочь физически',
		infinitive: 'can',
		pastSimple: 'could',
		pastParticiple: 'could',
		group: 1,
	},
	{
		id: 29,
		rus: 'бросать, лить (металл)',
		infinitive: 'cast',
		pastSimple: 'cast',
		pastParticiple: 'cast',
		group: 1,
	},
	{
		id: 30,
		rus: 'ловить, схватывать',
		infinitive: 'catch',
		pastSimple: 'caught',
		pastParticiple: 'caught',
		group: 1,
	},
	{
		id: 31,
		rus: 'выбирать',
		infinitive: 'choose',
		pastSimple: 'chose',
		pastParticiple: 'chosen',
		group: 1,
	},
	{
		id: 32,
		rus: 'прилипать, цеплять, льнуть',
		infinitive: 'cling',
		pastSimple: 'clung',
		pastParticiple: 'clung',
		group: 1,
	},
	{
		id: 33,
		rus: 'рассечь, расколоть',
		infinitive: 'cleave',
		pastSimple: 'cleft',
		pastParticiple: 'cloven',
		group: 1,
	},
	{
		id: 34,
		rus: 'одеть, одевать',
		infinitive: 'clothe',
		pastSimple: 'clothed',
		pastParticiple: 'clothed',
		group: 1,
	},
	{
		id: 35,
		rus: 'одеть, одевать',
		infinitive: 'come',
		pastSimple: 'came',
		pastParticiple: 'come',
		group: 1,
	},
	{
		id: 36,
		rus: 'оценивать, стоить',
		infinitive: 'cost',
		pastSimple: 'cost',
		pastParticiple: 'cost',
		group: 1,
	},
	{
		id: 37,
		rus: 'ползать',
		infinitive: 'creep',
		pastSimple: 'crept',
		pastParticiple: 'crept',
		group: 1,
	},
	{
		id: 38,
		rus: 'резать, обрезать',
		infinitive: 'cut',
		pastSimple: 'cut',
		pastParticiple: 'cut',
		group: 1,
	},
	{
		id: 39,
		rus: 'сметь',
		infinitive: 'dare',
		pastSimple: 'durst',
		pastParticiple: 'dared',
		group: 1,
	},
	{
		id: 40,
		rus: 'иметь дело, торговать, рассматривать вопрос',
		infinitive: 'deal',
		pastSimple: 'dealt',
		pastParticiple: 'dealt',
		group: 1,
	},
	{
		id: 41,
		rus: 'копать',
		infinitive: 'dig',
		pastSimple: 'dug',
		pastParticiple: 'dug',
		group: 1,
	},
	{
		id: 42,
		rus: 'нырять',
		infinitive: 'dive',
		pastSimple: 'dove',
		pastParticiple: 'dived',
		group: 1,
	},
	{
		id: 43,
		rus: 'делать',
		infinitive: 'do/does',
		pastSimple: 'did',
		pastParticiple: 'done',
		group: 1,
	},
	{
		id: 44,
		rus: 'тащить, чертить',
		infinitive: 'draw',
		pastSimple: 'drew',
		pastParticiple: 'drawn',
		group: 1,
	},
	{
		id: 45,
		rus: 'видеть сны, мечтать',
		infinitive: 'dream',
		pastSimple: 'dreamt',
		pastParticiple: 'dreamt',
		group: 1,
	},
	{
		id: 46,
		rus: 'пить, выпивать',
		infinitive: 'drink',
		pastSimple: 'drank',
		pastParticiple: 'drunk',
		group: 1,
	},
	{
		id: 47,
		rus: 'ехать, везти, водить, гнать',
		infinitive: 'drive',
		pastSimple: 'drove',
		pastParticiple: 'driven',
		group: 1,
	},
	{
		id: 48,
		rus: 'обитать, пребывать, задерживаться на чем-либо',
		infinitive: 'dwell',
		pastSimple: 'dwelt',
		pastParticiple: 'dwelt',
		group: 1,
	},
	{
		id: 49,
		rus: 'есть, принимать пищу, кушать',
		infinitive: 'eat',
		pastSimple: 'ate',
		pastParticiple: 'eaten',
		group: 1,
	},
	{
		id: 50,
		rus: 'падать',
		infinitive: 'fall',
		pastSimple: 'fell',
		pastParticiple: 'fallen',
		group: 1,
	},
	{
		id: 51,
		rus: 'кормить(ся)',
		infinitive: 'feed',
		pastSimple: 'fed',
		pastParticiple: 'fed',
		group: 1,
	},
	{
		id: 52,
		rus: 'чувствовать',
		infinitive: 'feel',
		pastSimple: 'felt',
		pastParticiple: 'felt',
		group: 1,
	},
	{
		id: 53,
		rus: 'бороться, сражаться, драться',
		infinitive: 'fight',
		pastSimple: 'fought',
		pastParticiple: 'fought',
		group: 1,
	},
	{
		id: 54,
		rus: 'находить',
		infinitive: 'find',
		pastSimple: 'found',
		pastParticiple: 'found',
		group: 1,
	},
	{
		id: 55,
		rus: 'подходить, годиться',
		infinitive: 'fit',
		pastSimple: 'fit',
		pastParticiple: 'fit',
		group: 1,
	},
	{
		id: 56,
		rus: 'бежать, спасаться бегством',
		infinitive: 'flee',
		pastSimple: 'fled',
		pastParticiple: 'fled',
		group: 1,
	},
	{
		id: 57,
		rus: 'кидать, бросать',
		infinitive: 'fling',
		pastSimple: 'flung',
		pastParticiple: 'flung',
		group: 1,
	},
	{
		id: 58,
		rus: 'летать, пролетать',
		infinitive: 'fly',
		pastSimple: 'flew',
		pastParticiple: 'flown',
		group: 1,
	},
	{
		id: 59,
		rus: 'запрещать',
		infinitive: 'forbid',
		pastSimple: 'forbade',
		pastParticiple: 'forbidden',
		group: 1,
	},
	{
		id: 60,
		rus: 'предвидеть, предсказывать',
		infinitive: 'forecast',
		pastSimple: 'forecast/forecasted',
		pastParticiple: 'forecast/forecasted',
		group: 1,
	},
	{
		id: 61,
		rus: 'забывать',
		infinitive: 'forget',
		pastSimple: 'forgot',
		pastParticiple: 'forgotten',
		group: 1,
	},
	{
		id: 62,
		rus: 'отказываться, воздерживаться',
		infinitive: 'forego',
		pastSimple: 'forewent',
		pastParticiple: 'foregone',
		group: 1,
	},
	{
		id: 63,
		rus: 'предсказывать, прогнозировать',
		infinitive: 'foretell',
		pastSimple: 'foretold',
		pastParticiple: 'foretold',
		group: 1,
	},
	{
		id: 64,
		rus: 'прощать',
		infinitive: 'forgive',
		pastSimple: 'forgave',
		pastParticiple: 'forgiven',
		group: 1,
	},
	{
		id: 65,
		rus: 'бросать, отказываться',
		infinitive: 'forsake',
		pastSimple: 'forsook',
		pastParticiple: 'forsaken',
		group: 1,
	},
	{
		id: 66,
		rus: 'замерзать, замораживать',
		infinitive: 'freeze',
		pastSimple: 'froze',
		pastParticiple: 'frozen',
		group: 1,
	},
	{
		id: 67,
		rus: 'получать, становиться',
		infinitive: 'get',
		pastSimple: 'got',
		pastParticiple: 'got',
		group: 1,
	},
	{
		id: 68,
		rus: 'позолотить',
		infinitive: 'gild',
		pastSimple: 'gilt/gilded',
		pastParticiple: 'gilt/gilded',
		group: 1,
	},
	{
		id: 69,
		rus: 'давать',
		infinitive: 'give',
		pastSimple: 'gave',
		pastParticiple: 'given',
		group: 1,
	},
	{
		id: 70,
		rus: 'идти, ехать',
		infinitive: 'go/goes',
		pastSimple: 'went',
		pastParticiple: 'gone',
		group: 1,
	},
	{
		id: 71,
		rus: 'молоть',
		infinitive: 'grind',
		pastSimple: 'ground',
		pastParticiple: 'ground',
		group: 1,
	},
	{
		id: 72,
		rus: 'расти, выращивать',
		infinitive: 'grow',
		pastSimple: 'grew',
		pastParticiple: 'grown',
		group: 1,
	},
	{
		id: 73,
		rus: 'висеть, вешать',
		infinitive: 'hang',
		pastSimple: 'hung/hanged',
		pastParticiple: 'hung/hanged',
		group: 1,
	},
	{
		id: 74,
		rus: 'иметь, обладать',
		infinitive: 'have',
		pastSimple: 'had',
		pastParticiple: 'had',
		group: 1,
	},
	{
		id: 75,
		rus: 'рубить, тесать',
		infinitive: 'hew',
		pastSimple: 'hewed',
		pastParticiple: 'hewed/hewn',
		group: 1,
	},
	{
		id: 76,
		rus: 'слышать',
		infinitive: 'hear',
		pastSimple: 'heard',
		pastParticiple: 'heard',
		group: 1,
	},
	{
		id: 77,
		rus: 'прятать, прятаться',
		infinitive: 'hide',
		pastSimple: 'hid',
		pastParticiple: 'hidden',
		group: 1,
	},
	{
		id: 78,
		rus: 'ударять, поражать',
		infinitive: 'hit',
		pastSimple: 'hit',
		pastParticiple: 'hit',
		group: 1,
	},
	{
		id: 79,
		rus: 'держать, поддерживать (владеть)',
		infinitive: 'hold',
		pastSimple: 'held',
		pastParticiple: 'held',
		group: 1,
	},
	{
		id: 80,
		rus: 'повредить, причинять боль, ранить',
		infinitive: 'hurt',
		pastSimple: 'hurt',
		pastParticiple: 'hurt',
		group: 1,
	},
	{
		id: 81,
		rus: 'держать, хранить',
		infinitive: 'keep',
		pastSimple: 'kept',
		pastParticiple: 'kept',
		group: 1,
	},
	{
		id: 82,
		rus: 'становиться на колени',
		infinitive: 'kneel',
		pastSimple: 'knelt/kneeled',
		pastParticiple: 'knelt/kneeled',
		group: 1,
	},
	{
		id: 83,
		rus: 'вязать',
		infinitive: 'knit',
		pastSimple: 'knit/knitted',
		pastParticiple: 'knit/knitted',
		group: 1,
	},
	{
		id: 84,
		rus: 'знать',
		infinitive: 'know',
		pastSimple: 'knew',
		pastParticiple: 'known',
		group: 1,
	},
	{
		id: 85,
		rus: 'класть',
		infinitive: 'lay',
		pastSimple: 'laid',
		pastParticiple: 'laid',
		group: 1,
	},
	{
		id: 86,
		rus: 'вести, сопровождать',
		infinitive: 'lead',
		pastSimple: 'led',
		pastParticiple: 'led',
		group: 1,
	},
	{
		id: 87,
		rus: 'опираться, прислоняться',
		infinitive: 'lean',
		pastSimple: 'leant/leaned',
		pastParticiple: 'leant/leaned',
		group: 1,
	},
	{
		id: 88,
		rus: 'прыгать',
		infinitive: 'leap',
		pastSimple: 'leapt/leaped',
		pastParticiple: 'leapt/leaped',
		group: 1,
	},
	{
		id: 89,
		rus: 'учиться, узнавать',
		infinitive: 'learn',
		pastSimple: 'learnt/learned',
		pastParticiple: 'learnt/learned',
		group: 1,
	},
	{
		id: 90,
		rus: 'оставлять, уезжать',
		infinitive: 'leave',
		pastSimple: 'left',
		pastParticiple: 'left',
		group: 1,
	},
	{
		id: 91,
		rus: 'одалживать, давать взаймы',
		infinitive: 'lend',
		pastSimple: 'lent',
		pastParticiple: 'lent',
		group: 1,
	},
	{
		id: 92,
		rus: 'позволять, сдавать в наём',
		infinitive: 'let',
		pastSimple: 'let',
		pastParticiple: 'let',
		group: 1,
	},
	{
		id: 93,
		rus: 'лежать',
		infinitive: 'lie',
		pastSimple: 'lay',
		pastParticiple: 'lain',
		group: 1,
	},
	{
		id: 94,
		rus: 'зажигать, освещать',
		infinitive: 'light',
		pastSimple: 'lit/lighted',
		pastParticiple: 'lit/lighted',
		group: 1,
	},
	{
		id: 95,
		rus: 'терять',
		infinitive: 'lose',
		pastSimple: 'lost',
		pastParticiple: 'lost',
		group: 1,
	},
	{
		id: 96,
		rus: 'делать, заставлять',
		infinitive: 'make',
		pastSimple: 'made',
		pastParticiple: 'made',
		group: 1,
	},
	{
		id: 97,
		rus: 'мочь, иметь право',
		infinitive: 'may',
		pastSimple: 'might',
		pastParticiple: 'might',
		group: 1,
	},
	{
		id: 98,
		rus: 'значить, подразумевать',
		infinitive: 'mean',
		pastSimple: 'meant',
		pastParticiple: 'meant',
		group: 1,
	},
	{
		id: 99,
		rus: 'встречать, знакомиться',
		infinitive: 'meet',
		pastSimple: 'met',
		pastParticiple: 'met',
		group: 1,
	},
	{
		id: 100,
		rus: 'ослышаться',
		infinitive: 'mishear',
		pastSimple: 'misheard',
		pastParticiple: 'misheard',
		group: 1,
	},
	{
		id: 101,
		rus: 'класть не на место',
		infinitive: 'mislay',
		pastSimple: 'mislaid',
		pastParticiple: 'mislaid',
		group: 1,
	},
	{
		id: 102,
		rus: 'ошибаться, заблуждаться',
		infinitive: 'mistake',
		pastSimple: 'mistook',
		pastParticiple: 'mistaken',
		group: 1,
	},
	{
		id: 103,
		rus: 'косить',
		infinitive: 'mow',
		pastSimple: 'mowed',
		pastParticiple: 'mown',
		group: 1,
	},
	{
		id: 104,
		rus: 'догнать',
		infinitive: 'overtake',
		pastSimple: 'overtook',
		pastParticiple: 'overtaken',
		group: 1,
	},
	{
		id: 105,
		rus: 'платить',
		infinitive: 'pay',
		pastSimple: 'paid',
		pastParticiple: 'paid',
		group: 1,
	},
	{
		id: 106,
		rus: 'доказывать, удостоверять',
		infinitive: 'prove',
		pastSimple: 'proved',
		pastParticiple: 'proved/proven',
		group: 1,
	},
	{
		id: 107,
		rus: 'класть',
		infinitive: 'put',
		pastSimple: 'put',
		pastParticiple: 'put',
		group: 1,
	},
	{
		id: 108,
		rus: 'оставлять, покидать',
		infinitive: 'quit',
		pastSimple: 'quit/quitted',
		pastParticiple: 'quit/quitted',
		group: 1,
	},
	{
		id: 109,
		rus: 'читать',
		infinitive: 'read',
		pastSimple: 'read/red',
		pastParticiple: 'read/red',
		group: 1,
	},
	{
		id: 110,
		rus: 'перестраивать, восстанавливать',
		infinitive: 'rebuild',
		pastSimple: 'rebuilt',
		pastParticiple: 'rebuilt',
		group: 1,
	},
	{
		id: 111,
		rus: 'освобождать, избавлять',
		infinitive: 'rid',
		pastSimple: 'rid/ridded',
		pastParticiple: 'rid/ridded',
		group: 1,
	},
	{
		id: 112,
		rus: 'ехать верхом',
		infinitive: 'ride',
		pastSimple: 'rode',
		pastParticiple: 'ridden',
		group: 1,
	},
	{
		id: 113,
		rus: 'звонить, звенеть',
		infinitive: 'ring',
		pastSimple: 'rang',
		pastParticiple: 'rung',
		group: 1,
	},
	{
		id: 114,
		rus: 'подниматься, восходить',
		infinitive: 'rise',
		pastSimple: 'rose',
		pastParticiple: 'risen',
		group: 1,
	},
	{
		id: 115,
		rus: 'бежать, течь',
		infinitive: 'run',
		pastSimple: 'ran',
		pastParticiple: 'run',
		group: 1,
	},
	{
		id: 116,
		rus: 'пилить',
		infinitive: 'saw',
		pastSimple: 'sawed',
		pastParticiple: 'sawn/sawed',
		group: 1,
	},
	{
		id: 117,
		rus: 'говорить, сказать',
		infinitive: 'say',
		pastSimple: 'said',
		pastParticiple: 'said',
		group: 1,
	},
	{
		id: 118,
		rus: 'видеть',
		infinitive: 'see',
		pastSimple: 'saw',
		pastParticiple: 'seen',
		group: 1,
	},
	{
		id: 119,
		rus: 'искать',
		infinitive: 'seek',
		pastSimple: 'sought',
		pastParticiple: 'sought',
		group: 1,
	},
	{
		id: 120,
		rus: 'продавать',
		infinitive: 'sell',
		pastSimple: 'sold',
		pastParticiple: 'sold',
		group: 1,
	},
	{
		id: 121,
		rus: 'посылать, отправлять',
		infinitive: 'send',
		pastSimple: 'sent',
		pastParticiple: 'sent',
		group: 1,
	},
	{
		id: 122,
		rus: 'помещать, ставить',
		infinitive: 'set',
		pastSimple: 'set',
		pastParticiple: 'set',
		group: 1,
	},
	{
		id: 123,
		rus: 'шить',
		infinitive: 'sew',
		pastSimple: 'sewed',
		pastParticiple: 'sewed/sewn',
		group: 1,
	},
	{
		id: 124,
		rus: 'трясти',
		infinitive: 'shake',
		pastSimple: 'shook',
		pastParticiple: 'shaken',
		group: 1,
	},
	{
		id: 125,
		rus: 'быть должным',
		infinitive: 'shall',
		pastSimple: 'should',
		pastParticiple: 'should',
		group: 1,
	},
	{
		id: 126,
		rus: 'брить(ся)',
		infinitive: 'shave',
		pastSimple: 'shaved',
		pastParticiple: 'shaved',
		group: 1,
	},
	{
		id: 127,
		rus: 'стричь, резать; лишать',
		infinitive: 'shear',
		pastSimple: 'sheared',
		pastParticiple: 'shorn',
		group: 1,
	},
	{
		id: 128,
		rus: 'сбрасывать, проливать',
		infinitive: 'shed',
		pastSimple: 'shed',
		pastParticiple: 'shed',
		group: 1,
	},
	{
		id: 129,
		rus: 'сиять, светить',
		infinitive: 'shine',
		pastSimple: 'shone/shined',
		pastParticiple: 'shone/shined',
		group: 1,
	},
	{
		id: 130,
		rus: 'обувать, подковывать',
		infinitive: '	shoe',
		pastSimple: 'shod',
		pastParticiple: 'shod',
		group: 1,
	},
];

global.verbsList = verbsList;
global.levels = levels;
global.verbForms = verbForms;

export default global;