const global = {};

// functions

let toMixArray = (array) => {
	var currentIndex = array.length,
		temporaryValue, randomIndex;
	while (0 !== currentIndex) {
		randomIndex = Math.floor(Math.random() * currentIndex);
		currentIndex -= 1;
		temporaryValue = array[currentIndex];
		array[currentIndex] = array[randomIndex];
		array[randomIndex] = temporaryValue;
	}

	return array;
};

let toCompareTwoObjects = (obj1, obj2) => {
	let comparisonObj = {};
	if (Object.keys(obj1).length === 0 || Object.keys(obj2).length === 0) {
		return false;
	} else {
		let compar;
		for (let k in obj1) {
			if (obj1[k] === obj2[k]) {
				compar = 'success';
			} else {
				compar = 'error';
			}

			comparisonObj[k] = compar;
		}
	}

	return comparisonObj;
};

let toResultTest = (answerArray) => {
	let resultArr = [];

	for (let i = 0; i < answerArray.length; i++) {
		let result = true;
		for (let k in answerArray[i]) {

			if (answerArray[i][k] === 'error') {
				result = false;
			}
		}
		resultArr[i] = result;
	}

	return resultArr;
};

let toEqualTwoArrs = (arr1, arr2) => {
	for(let k in arr1) {
		for(let k in arr2) {
			if(arr1[k] !== arr2[k]) {
					return false
			}
		}
	}
	return true;
}

global.toMixArray = toMixArray;
global.toCompareTwoObjects = toCompareTwoObjects;
global.toResultTest = toResultTest;
global.toEqualTwoArrs = toEqualTwoArrs;

// vars

const phrases = [{
		id: 1,
		level: 1,
		rus: 'Это очень мило с вашей стороны!',
		eng: 'It is very kind of you',
	},
	{
		id: 2,
		level: 1,
		rus: 'Рад встрече с тобой!',
		eng: 'Nice meet you',
	},
];

const levels = [{
		level: 0,
		name: 'zero',
		amount: 3,
		descr: 'Уровень 0: (Ноль). Вам предстоит пройти тест всего из 10 неправильных глаголов, которые будут сгенерированы из группы глаголов №1',
		verbsGroups: [1],
	},
	{
		level: 1,
		name: 'dummy',
		amount: 20,
		descr: 'Уровень 1: (Болван). Вам предстоит пройти тест из 20 неправильных глаголов, которые будут сгенерированы из группы глаголов №1',
		verbsGroups: [1],
	},
	{
		level: 2,
		name: 'schoolkid',
		amount: 30,
		descr: 'Уровень 2: (Школьник). Вам предстоит пройти тест из 30 неправильных глаголов, которые будут сгенерированы из групп глаголов №№ 1 и 2',
		verbsGroups: [1, 2],
	},
	{
		level: 3,
		name: 'middle',
		amount: 40,
		descr: 'Уровень 3: (Средний). Вам предстоит пройти тест из 40 неправильных глаголов, которые будут сгенерированы из групп глаголов №№ 1 и 2',
		verbsGroups: [1, 2],
	},
	{
		level: 4,
		name: 'veteran',
		amount: 50,
		descr: 'Уровень 4: (Ветеран). Вам предстоит пройти тест из 50 неправильных глаголов, которые будут сгенерированы из групп глаголов №№ 1, 2, 3',
		verbsGroups: [1, 2, 3],
	},
	{
		level: 5,
		name: 'expert',
		amount: 65,
		descr: 'Уровень 5: (Эксперт). Вам предстоит пройти тест из 65 неправильных глаголов, которые будут сгенерированы из групп глаголов №№ 1, 2, 3',
		verbsGroups: [1, 2, 3],
	},
	{
		level: 6,
		name: 'God',
		amount: 80,
		descr: 'Уровень 6: (Божество). Вам предстоит пройти тест из 80 неправильных глаголов, которые будут сгенерированы из групп глаголов №№ 1, 2, 3, 4',
		verbsGroups: [1, 2, 3, 4],
	},
];

const verbForms = [{
		id: 1,
		name: 'infinitive',
		var: 'infinitive'
	},
	{
		id: 2,
		name: 'past simple',
		var: 'pastSimple'
	},
	{
		id: 3,
		name: 'past participle',
		var: 'pastParticiple'
	}
];

const verbsList = [{
		id: 1,
		rus: 'соблюдать, придерживаться чего-либо, пребывать',
		infinitive: 'abide',
		pastSimple: 'abode',
		pastParticiple: 'abode',
		group: 4,
		type: 1,
	},
	{
		id: 2,
		rus: 'возникать, подниматься',
		infinitive: 'arise',
		pastSimple: 'arose',
		pastParticiple: 'arisen',
		group: 2,
		type: 1,
	},
	{
		id: 3,
		rus: 'будить, просыпаться',
		infinitive: 'awake',
		pastSimple: 'awoke',
		pastParticiple: 'awoken',
		group: 2,
		type: 1,
	},
	{
		id: 4,
		rus: 'быть, являться',
		infinitive: 'be',
		pastSimple: 'was/were',
		pastParticiple: 'been',
		group: 1,
		type: 1,
	},
	{
		id: 5,
		rus: 'рождать, рожать',
		infinitive: 'bear',
		pastSimple: 'bore',
		pastParticiple: 'born',
		group: 1,
		type: 1,
	},
	{
		id: 6,
		rus: 'бить',
		infinitive: 'beat',
		pastSimple: 'beat',
		pastParticiple: 'beaten',
		group: 1,
		type: 1,
	},
	{
		id: 7,
		rus: 'становиться, делаться',
		infinitive: 'become',
		pastSimple: 'became',
		pastParticiple: 'become',
		group: 1,
		type: 1,
	},

	{
		id: 8,
		rus: 'случаться',
		infinitive: 'befall',
		pastSimple: 'befell',
		pastParticiple: 'befallen',
		group: 3,
		type: 1,
	},
	{
		id: 9,
		rus: 'начинать(ся)',
		infinitive: 'begin',
		pastSimple: 'began',
		pastParticiple: 'begun',
		group: 1,
		type: 1,
	},
	{
		id: 10,
		rus: 'вглядываться, замечать',
		infinitive: 'behold',
		pastSimple: 'beheld',
		pastParticiple: 'beheld',
		group: 4,
		type: 1,
	},
	{
		id: 11,
		rus: 'гнуть(ся), сгибать(ся)',
		infinitive: 'bend',
		pastSimple: 'bent',
		pastParticiple: 'bent',
		group: 2,
		type: 1,
	},
	{
		id: 12,
		rus: 'умолять, упрашивать',
		infinitive: 'beseech',
		pastSimple: 'besought',
		pastParticiple: 'besought',
		group: 4,
		type: 1,
	},
	{
		id: 13,
		rus: 'окружать, осаждать',
		infinitive: 'beset',
		pastSimple: 'beset',
		pastParticiple: 'beset',
		group: 3,
		type: 1,
	},
	{
		id: 14,
		rus: 'держать пари',
		infinitive: 'bet',
		pastSimple: 'bet',
		pastParticiple: 'bet',
		group: 3,
		type: 1,
	},
	{
		id: 15,
		rus: 'предлагать цену, велеть, просить',
		infinitive: 'bid',
		pastSimple: 'bid',
		pastParticiple: 'bid',
		group: 3,
		type: 1,
	},
	{
		id: 16,
		rus: 'связывать',
		infinitive: 'bind',
		pastSimple: 'bound',
		pastParticiple: 'bound',
		group: 2,
		type: 1,
	},
	{
		id: 17,
		rus: 'кусать(ся)',
		infinitive: 'bite',
		pastSimple: 'bit',
		pastParticiple: 'bitten',
		group: 2,
		type: 1,
	},
	{
		id: 18,
		rus: 'кровоточить, опорожнять',
		infinitive: 'bleed',
		pastSimple: 'bled',
		pastParticiple: 'bled',
		group: 3,
		type: 1,
	},
	{
		id: 19,
		rus: 'дуть',
		infinitive: 'blow',
		pastSimple: 'blew',
		pastParticiple: 'blown',
		group: 3,
		type: 1,
	},
	{
		id: 20,
		rus: 'ломать, прерывать, разбивать',
		infinitive: 'break',
		pastSimple: 'broke',
		pastParticiple: 'broken',
		group: 1,
		type: 1,
	},
	{
		id: 21,
		rus: 'порождать, разводить, выводить',
		infinitive: 'breed',
		pastSimple: 'bred',
		pastParticiple: 'bred',
		group: 2,
		type: 1,
	},
	{
		id: 22,
		rus: 'приносить, приводить',
		infinitive: 'bring',
		pastSimple: 'brought',
		pastParticiple: 'brought',
		group: 1,
		type: 1,
	},
	{
		id: 23,
		rus: 'вещать, распространять',
		infinitive: 'broadcast',
		pastSimple: 'broadcast',
		pastParticiple: 'broadcast',
		group: 3,
		type: 1,
	},
	{
		id: 24,
		rus: 'строить, встраивать',
		infinitive: 'build',
		pastSimple: 'built',
		pastParticiple: 'built',
		group: 1,
		type: 1,
	},
	{
		id: 25,
		rus: 'гореть, сжигать',
		infinitive: 'burn',
		pastSimple: 'burnt',
		pastParticiple: 'burnt',
		group: 2,
		type: 1,
	},
	{
		id: 26,
		rus: 'взрывать(ся)',
		infinitive: 'burst',
		pastSimple: 'burst',
		pastParticiple: 'burst',
		group: 3,
		type: 1,
	},
	{
		id: 27,
		rus: 'покупать',
		infinitive: 'buy',
		pastSimple: 'bought',
		pastParticiple: 'bought',
		group: 1,
		type: 1,
	},
	{
		id: 28,
		rus: 'мочь физически',
		infinitive: 'can',
		pastSimple: 'could',
		pastParticiple: 'could',
		group: 1,
		type: 1,
	},
	{
		id: 29,
		rus: 'бросать, лить (металл)',
		infinitive: 'cast',
		pastSimple: 'cast',
		pastParticiple: 'cast',
		group: 3,
		type: 1,
	},
	{
		id: 30,
		rus: 'ловить, схватывать',
		infinitive: 'catch',
		pastSimple: 'caught',
		pastParticiple: 'caught',
		group: 2,
		type: 1,
	},
	{
		id: 31,
		rus: 'выбирать',
		infinitive: 'choose',
		pastSimple: 'chose',
		pastParticiple: 'chosen',
		group: 1,
		type: 1,
	},
	{
		id: 32,
		rus: 'прилипать, цеплять, льнуть',
		infinitive: 'cling',
		pastSimple: 'clung',
		pastParticiple: 'clung',
		group: 3,
		type: 1,
	},
	{
		id: 33,
		rus: 'рассечь, расколоть',
		infinitive: 'cleave',
		pastSimple: 'cleft',
		pastParticiple: 'cloven',
		group: 3,
		type: 1,
	},
	{
		id: 34,
		rus: 'одеть, одевать',
		infinitive: 'clothe',
		pastSimple: 'clothed',
		pastParticiple: 'clothed',
		group: 3,
		type: 1,
	},
	{
		id: 35,
		rus: 'приходить, приезжать',
		infinitive: 'come',
		pastSimple: 'came',
		pastParticiple: 'come',
		group: 1,
		type: 1,
	},
	{
		id: 36,
		rus: 'оценивать, стоить',
		infinitive: 'cost',
		pastSimple: 'cost',
		pastParticiple: 'cost',
		group: 1,
		type: 1,
	},
	{
		id: 37,
		rus: 'ползать',
		infinitive: 'creep',
		pastSimple: 'crept',
		pastParticiple: 'crept',
		group: 3,
		type: 1,
	},
	{
		id: 38,
		rus: 'резать, обрезать',
		infinitive: 'cut',
		pastSimple: 'cut',
		pastParticiple: 'cut',
		group: 2,
		type: 1,
	},
	{
		id: 39,
		rus: 'сметь, дерзать',
		infinitive: 'dare',
		pastSimple: 'durst',
		pastParticiple: 'dared',
		group: 3,
		type: 1,
	},
	{
		id: 40,
		rus: 'торговать, иметь дело, рассматривать вопрос',
		infinitive: 'deal',
		pastSimple: 'dealt',
		pastParticiple: 'dealt',
		group: 2,
		type: 1,
	},
	{
		id: 41,
		rus: 'копать',
		infinitive: 'dig',
		pastSimple: 'dug',
		pastParticiple: 'dug',
		group: 2,
		type: 1,
	},
	{
		id: 42,
		rus: 'нырять',
		infinitive: 'dive',
		pastSimple: 'dove',
		pastParticiple: 'dived',
		group: 2,
		type: 1,
	},
	{
		id: 43,
		rus: 'делать',
		infinitive: 'do',
		pastSimple: 'did',
		pastParticiple: 'done',
		group: 1,
		type: 1,
	},
	{
		id: 44,
		rus: 'тащить, чертить',
		infinitive: 'draw',
		pastSimple: 'drew',
		pastParticiple: 'drawn',
		group: 2,
		type: 1,
	},
	{
		id: 45,
		rus: 'видеть сны, мечтать',
		infinitive: 'dream',
		pastSimple: 'dreamt',
		pastParticiple: 'dreamt',
		group: 2,
		type: 1,
	},
	{
		id: 46,
		rus: 'пить, выпивать',
		infinitive: 'drink',
		pastSimple: 'drank',
		pastParticiple: 'drunk',
		group: 2,
		type: 1,
	},
	{
		id: 47,
		rus: 'ехать, везти, водить, гнать',
		infinitive: 'drive',
		pastSimple: 'drove',
		pastParticiple: 'driven',
		group: 1,
		type: 1,
	},
	{
		id: 48,
		rus: 'обитать, пребывать, задерживаться на чем-либо',
		infinitive: 'dwell',
		pastSimple: 'dwelt',
		pastParticiple: 'dwelt',
		group: 3,
		type: 1,
	},
	{
		id: 49,
		rus: 'есть, принимать пищу, кушать',
		infinitive: 'eat',
		pastSimple: 'ate',
		pastParticiple: 'eaten',
		group: 1,
		type: 1,
	},
	{
		id: 50,
		rus: 'падать',
		infinitive: 'fall',
		pastSimple: 'fell',
		pastParticiple: 'fallen',
		group: 1,
		type: 1,
	},
	{
		id: 51,
		rus: 'кормить(ся)',
		infinitive: 'feed',
		pastSimple: 'fed',
		pastParticiple: 'fed',
		group: 2,
		type: 1,
	},
	{
		id: 52,
		rus: 'чувствовать',
		infinitive: 'feel',
		pastSimple: 'felt',
		pastParticiple: 'felt',
		group: 1,
		type: 1,
	},
	{
		id: 53,
		rus: 'бороться, сражаться, драться',
		infinitive: 'fight',
		pastSimple: 'fought',
		pastParticiple: 'fought',
		group: 2,
		type: 1,
	},
	{
		id: 54,
		rus: 'находить',
		infinitive: 'find',
		pastSimple: 'found',
		pastParticiple: 'found',
		group: 1,
		type: 1,
	},
	{
		id: 55,
		rus: 'подходить, годиться',
		infinitive: 'fit',
		pastSimple: 'fit',
		pastParticiple: 'fit',
		group: 3,
		type: 1,
	},
	{
		id: 56,
		rus: 'бежать, спасаться бегством',
		infinitive: 'flee',
		pastSimple: 'fled',
		pastParticiple: 'fled',
		group: 3,
		type: 1,
	},
	{
		id: 57,
		rus: 'кидать, бросать',
		infinitive: 'fling',
		pastSimple: 'flung',
		pastParticiple: 'flung',
		group: 4,
		type: 1,
	},
	{
		id: 58,
		rus: 'летать, пролетать',
		infinitive: 'fly',
		pastSimple: 'flew',
		pastParticiple: 'flown',
		group: 1,
		type: 1,
	},
	{
		id: 59,
		rus: 'запрещать',
		infinitive: 'forbid',
		pastSimple: 'forbade',
		pastParticiple: 'forbidden',
		group: 3,
		type: 1,
	},
	{
		id: 60,
		rus: 'предвидеть, предсказывать',
		infinitive: 'forecast',
		pastSimple: 'forecast',
		pastParticiple: 'forecast',
		group: 3,
		type: 1,
	},
	{
		id: 61,
		rus: 'забывать',
		infinitive: 'forget',
		pastSimple: 'forgot',
		pastParticiple: 'forgotten',
		group: 2,
		type: 1,
	},
	{
		id: 62,
		rus: 'отказываться, воздерживаться',
		infinitive: 'forego',
		pastSimple: 'forewent',
		pastParticiple: 'foregone',
		group: 3,
		type: 1,
	},
	{
		id: 63,
		rus: 'предсказывать, прогнозировать',
		infinitive: 'foretell',
		pastSimple: 'foretold',
		pastParticiple: 'foretold',
		group: 3,
		type: 1,
	},
	{
		id: 64,
		rus: 'прощать',
		infinitive: 'forgive',
		pastSimple: 'forgave',
		pastParticiple: 'forgiven',
		group: 2,
		type: 1,
	},
	{
		id: 65,
		rus: 'бросать, отказываться',
		infinitive: 'forsake',
		pastSimple: 'forsook',
		pastParticiple: 'forsaken',
		group: 4,
		type: 1,
	},
	{
		id: 66,
		rus: 'замерзать, замораживать',
		infinitive: 'freeze',
		pastSimple: 'froze',
		pastParticiple: 'frozen',
		group: 1,
		type: 1,
	},
	{
		id: 67,
		rus: 'получать, становиться',
		infinitive: 'get',
		pastSimple: 'got',
		pastParticiple: 'got',
		group: 1,
		type: 1,
	},
	{
		id: 68,
		rus: 'позолотить',
		infinitive: 'gild',
		pastSimple: 'gilt',
		pastParticiple: 'gilt',
		group: 4,
		type: 1,
	},
	{
		id: 69,
		rus: 'давать',
		infinitive: 'give',
		pastSimple: 'gave',
		pastParticiple: 'given',
		group: 1,
		type: 1,
	},
	{
		id: 70,
		rus: 'идти, ехать',
		infinitive: 'go/goes',
		pastSimple: 'went',
		pastParticiple: 'gone',
		group: 1,
		type: 1,
	},
	{
		id: 71,
		rus: 'молоть',
		infinitive: 'grind',
		pastSimple: 'ground',
		pastParticiple: 'ground',
		group: 3,
		type: 1,
	},
	{
		id: 72,
		rus: 'расти, выращивать',
		infinitive: 'grow',
		pastSimple: 'grew',
		pastParticiple: 'grown',
		group: 2,
		type: 1,
	},
	{
		id: 73,
		rus: 'висеть, вешать',
		infinitive: 'hang',
		pastSimple: 'hung',
		pastParticiple: 'hung',
		group: 3,
		type: 1,
	},
	{
		id: 74,
		rus: 'иметь, обладать',
		infinitive: 'have',
		pastSimple: 'had',
		pastParticiple: 'had',
		group: 1,
		type: 1,
	},
	// {
	// 	id: 75,
	// 	rus: 'рубить, тесать',
	// 	infinitive: 'hew',
	// 	pastSimple: 'hewed',
	// 	pastParticiple: 'hewed/hewn',
	// 	group: 4,
	// 	type: 1,
	// },
	{
		id: 76,
		rus: 'слышать',
		infinitive: 'hear',
		pastSimple: 'heard',
		pastParticiple: 'heard',
		group: 1,
		type: 1,
	},
	{
		id: 77,
		rus: 'прятать, прятаться',
		infinitive: 'hide',
		pastSimple: 'hid',
		pastParticiple: 'hidden',
		group: 2,
		type: 1,
	},
	{
		id: 78,
		rus: 'ударять, поражать',
		infinitive: 'hit',
		pastSimple: 'hit',
		pastParticiple: 'hit',
		group: 3,
		type: 1,
	},
	{
		id: 79,
		rus: 'держать, поддерживать (владеть)',
		infinitive: 'hold',
		pastSimple: 'held',
		pastParticiple: 'held',
		group: 1,
		type: 1,
	},
	{
		id: 80,
		rus: 'повредить, причинять боль, ранить',
		infinitive: 'hurt',
		pastSimple: 'hurt',
		pastParticiple: 'hurt',
		group: 3,
		type: 1,
	},
	{
		id: 81,
		rus: 'держать, хранить',
		infinitive: 'keep',
		pastSimple: 'kept',
		pastParticiple: 'kept',
		group: 2,
		type: 1,
	},
	{
		id: 82,
		rus: 'становиться на колени',
		infinitive: 'kneel',
		pastSimple: 'knelt',
		pastParticiple: 'knelt',
		group: 3,
		type: 1,
	},
	{
		id: 83,
		rus: 'вязать',
		infinitive: 'knit',
		pastSimple: 'knit',
		pastParticiple: 'knit',
		group: 3,
		type: 1,
	},
	{
		id: 84,
		rus: 'знать',
		infinitive: 'know',
		pastSimple: 'knew',
		pastParticiple: 'known',
		group: 1,
		type: 1,
	},
	{
		id: 85,
		rus: 'прокладывать, класть',
		infinitive: 'lay',
		pastSimple: 'laid',
		pastParticiple: 'laid',
		group: 3,
		type: 1,
	},
	{
		id: 86,
		rus: 'вести, сопровождать',
		infinitive: 'lead',
		pastSimple: 'led',
		pastParticiple: 'led',
		group: 2,
		type: 1,
	},
	{
		id: 87,
		rus: 'опираться, прислоняться',
		infinitive: 'lean',
		pastSimple: 'leant',
		pastParticiple: 'leant',
		group: 3,
		type: 1,
	},
	{
		id: 88,
		rus: 'скакать, прыгать',
		infinitive: 'leap',
		pastSimple: 'leapt',
		pastParticiple: 'leapt',
		group: 3,
		type: 1,
	},
	{
		id: 89,
		rus: 'учиться, узнавать',
		infinitive: 'learn',
		pastSimple: 'learnt',
		pastParticiple: 'learnt',
		group: 1,
		type: 1,
	},
	{
		id: 90,
		rus: 'оставлять, уезжать',
		infinitive: 'leave',
		pastSimple: 'left',
		pastParticiple: 'left',
		group: 1,
		type: 1,
	},
	{
		id: 91,
		rus: 'одалживать, давать взаймы',
		infinitive: 'lend',
		pastSimple: 'lent',
		pastParticiple: 'lent',
		group: 3,
		type: 1,
	},
	{
		id: 92,
		rus: 'позволять, сдавать в наём',
		infinitive: 'let',
		pastSimple: 'let',
		pastParticiple: 'let',
		group: 3,
		type: 1,
	},
	{
		id: 93,
		rus: 'лежать',
		infinitive: 'lie',
		pastSimple: 'lay',
		pastParticiple: 'lain',
		group: 1,
		type: 1,
	},
	{
		id: 94,
		rus: 'зажигать, освещать',
		infinitive: 'light',
		pastSimple: 'lit',
		pastParticiple: 'lit',
		group: 2,
		type: 1,
	},
	{
		id: 95,
		rus: 'терять',
		infinitive: 'lose',
		pastSimple: 'lost',
		pastParticiple: 'lost',
		group: 2,
		type: 1,
	},
	{
		id: 96,
		rus: 'делать, заставлять',
		infinitive: 'make',
		pastSimple: 'made',
		pastParticiple: 'made',
		group: 1,
		type: 1,
	},
	{
		id: 97,
		rus: 'мочь, иметь право',
		infinitive: 'may',
		pastSimple: 'might',
		pastParticiple: 'might',
		group: 1,
		type: 1,
	},
	{
		id: 98,
		rus: 'иметь в виду, значить, подразумевать',
		infinitive: 'mean',
		pastSimple: 'meant',
		pastParticiple: 'meant',
		group: 3,
		type: 1,
	},
	{
		id: 99,
		rus: 'встречать, знакомиться',
		infinitive: 'meet',
		pastSimple: 'met',
		pastParticiple: 'met',
		group: 1,
		type: 1,
	},
	{
		id: 100,
		rus: 'ослышаться',
		infinitive: 'mishear',
		pastSimple: 'misheard',
		pastParticiple: 'misheard',
		group: 3,
		type: 1,
	},
	{
		id: 101,
		rus: 'класть не на место',
		infinitive: 'mislay',
		pastSimple: 'mislaid',
		pastParticiple: 'mislaid',
		group: 3,
		type: 1,
	},
	{
		id: 102,
		rus: 'ошибаться, заблуждаться',
		infinitive: 'mistake',
		pastSimple: 'mistook',
		pastParticiple: 'mistaken',
		group: 2,
		type: 1,
	},
	{
		id: 103,
		rus: 'косить, скирдовать, жать',
		infinitive: 'mow',
		pastSimple: 'mowed',
		pastParticiple: 'mown',
		group: 3,
		type: 1,
	},
	{
		id: 104,
		rus: 'настигать, догнать',
		infinitive: 'overtake',
		pastSimple: 'overtook',
		pastParticiple: 'overtaken',
		group: 3,
		type: 1,
	},
	{
		id: 105,
		rus: 'платить',
		infinitive: 'pay',
		pastSimple: 'paid',
		pastParticiple: 'paid',
		group: 1,
		type: 1,
	},
	// {
	// 	id: 106,
	// 	rus: 'доказывать, удостоверять',
	// 	infinitive: 'prove',
	// 	pastSimple: 'proved',
	// 	pastParticiple: 'proved/proven',
	// 	group: 3,
	// 	type: 1,
	// },
	{
		id: 107,
		rus: 'класть',
		infinitive: 'put',
		pastSimple: 'put',
		pastParticiple: 'put',
		group: 1,
		type: 1,
	},
	{
		id: 108,
		rus: 'оставлять, покидать',
		infinitive: 'quit',
		pastSimple: 'quit',
		pastParticiple: 'quit',
		group: 2,
		type: 1,
	},
	{
		id: 109,
		rus: 'читать',
		infinitive: 'read',
		pastSimple: 'read',
		pastParticiple: 'read',
		group: 1,
		type: 1,
	},
	{
		id: 110,
		rus: 'перестраивать, восстанавливать',
		infinitive: 'rebuild',
		pastSimple: 'rebuilt',
		pastParticiple: 'rebuilt',
		group: 3,
		type: 1,
	},
	{
		id: 111,
		rus: 'освобождать, избавлять',
		infinitive: 'rid',
		pastSimple: 'rid',
		pastParticiple: 'rid',
		group: 3,
		type: 1,
	},
	{
		id: 112,
		rus: 'ехать верхом',
		infinitive: 'ride',
		pastSimple: 'rode',
		pastParticiple: 'ridden',
		group: 2,
		type: 1,
	},
	{
		id: 113,
		rus: 'звонить, звенеть',
		infinitive: 'ring',
		pastSimple: 'rang',
		pastParticiple: 'rung',
		group: 2,
		type: 1,
	},
	{
		id: 114,
		rus: 'подниматься, восходить',
		infinitive: 'rise',
		pastSimple: 'rose',
		pastParticiple: 'risen',
		group: 2,
		type: 1,
	},
	{
		id: 115,
		rus: 'бежать, течь',
		infinitive: 'run',
		pastSimple: 'ran',
		pastParticiple: 'run',
		group: 1,
		type: 1,
	},
	{
		id: 116,
		rus: 'пилить',
		infinitive: 'saw',
		pastSimple: 'sawed',
		pastParticiple: 'sawn',
		group: 2,
		type: 1,
	},
	{
		id: 117,
		rus: 'говорить, сказать',
		infinitive: 'say',
		pastSimple: 'said',
		pastParticiple: 'said',
		group: 1,
		type: 1,
	},
	{
		id: 118,
		rus: 'видеть',
		infinitive: 'see',
		pastSimple: 'saw',
		pastParticiple: 'seen',
		group: 1,
		type: 1,
	},
	{
		id: 119,
		rus: 'искать, стремиться, добиваться',
		infinitive: 'seek',
		pastSimple: 'sought',
		pastParticiple: 'sought',
		group: 3,
		type: 1,
	},
	{
		id: 120,
		rus: 'продавать',
		infinitive: 'sell',
		pastSimple: 'sold',
		pastParticiple: 'sold',
		group: 1,
		type: 1,
	},
	{
		id: 121,
		rus: 'посылать, отправлять',
		infinitive: 'send',
		pastSimple: 'sent',
		pastParticiple: 'sent',
		group: 1,
		type: 1,
	},
	{
		id: 122,
		rus: 'помещать, ставить',
		infinitive: 'set',
		pastSimple: 'set',
		pastParticiple: 'set',
		group: 1,
		type: 1,
	},
	// {
	// 	id: 123,
	// 	rus: 'шить',
	// 	infinitive: 'sew',
	// 	pastSimple: 'sewed',
	// 	pastParticiple: 'sewed/sewn',
	// 	group: 3,
	// 	type: 1,
	// },
	{
		id: 124,
		rus: 'трясти',
		infinitive: 'shake',
		pastSimple: 'shook',
		pastParticiple: 'shaken',
		group: 3,
		type: 1,
	},
	{
		id: 125,
		rus: 'быть должным',
		infinitive: 'shall',
		pastSimple: 'should',
		pastParticiple: 'should',
		group: 1,
		type: 1,
	},
	{
		id: 126,
		rus: 'брить(ся)',
		infinitive: 'shave',
		pastSimple: 'shaved',
		pastParticiple: 'shaved',
		group: 2,
		type: 1,
	},
	{
		id: 127,
		rus: 'стричь, резать; лишать',
		infinitive: 'shear',
		pastSimple: 'sheared',
		pastParticiple: 'shorn',
		group: 4,
		type: 1,
	},
	{
		id: 128,
		rus: 'сбрасывать, проливать',
		infinitive: 'shed',
		pastSimple: 'shed',
		pastParticiple: 'shed',
		group: 3,
		type: 1,
	},
	{
		id: 129,
		rus: 'сиять, светить',
		infinitive: 'shine',
		pastSimple: 'shone',
		pastParticiple: 'shone',
		group: 2,
		type: 1,
	},
	{
		id: 130,
		rus: 'обувать, подковывать',
		infinitive: 'shoe',
		pastSimple: 'shod',
		pastParticiple: 'shod',
		group: 2,
		type: 1,
	},
	{
		id: 131,
		rus: 'стрелять',
		infinitive: 'shoot',
		pastSimple: 'shot',
		pastParticiple: 'shot',
		group: 2,
		type: 1,
	},
	{
		id: 132,
		rus: 'показывать',
		infinitive: 'show',
		pastSimple: 'showed',
		pastParticiple: 'shown',
		group: 1,
		type: 1,
	},
	{
		id: 133,
		rus: 'сокращаться, сжиматься, отскочить, отпрянуть',
		infinitive: 'shrink',
		pastSimple: 'shrank',
		pastParticiple: 'shrunk',
		group: 3,
		type: 1,
	},
	{
		id: 134,
		rus: 'закрывать',
		infinitive: 'shut',
		pastSimple: 'shut',
		pastParticiple: 'shut',
		group: 2,
		type: 1,
	},
	{
		id: 135,
		rus: 'петь',
		infinitive: 'sing',
		pastSimple: 'sang',
		pastParticiple: 'sung',
		group: 2,
		type: 1,
	},
	{
		id: 136,
		rus: 'опускаться, погружаться, тонуть',
		infinitive: 'sink',
		pastSimple: 'sank',
		pastParticiple: 'sunk',
		group: 3,
		type: 1,
	},
	{
		id: 137,
		rus: 'сидеть',
		infinitive: 'sit',
		pastSimple: 'sat',
		pastParticiple: 'sat',
		group: 1,
		type: 1,
	},
	{
		id: 138,
		rus: 'убивать, уничтожать',
		infinitive: 'slay',
		pastSimple: 'slew',
		pastParticiple: 'slain',
		group: 2,
		type: 1,
	},
	{
		id: 139,
		rus: 'спать',
		infinitive: 'sleep',
		pastSimple: 'slept',
		pastParticiple: 'slept',
		group: 1,
		type: 1,
	},
	{
		id: 140,
		rus: 'скользить',
		infinitive: 'slide',
		pastSimple: 'slid',
		pastParticiple: 'slid',
		group: 2,
		type: 1,
	},
	{
		id: 141,
		rus: 'метать, швырять, швырнуть, вешать через плечо, подвешивать',
		infinitive: 'sling',
		pastSimple: 'slung',
		pastParticiple: 'slung',
		group: 4,
		type: 1,
	},
	{
		id: 142,
		rus: 'резать в длину, вдоль',
		infinitive: 'slit',
		pastSimple: 'slit',
		pastParticiple: 'slit',
		group: 3,
		type: 1,
	},
	{
		id: 143,
		rus: 'пахнуть, нюхать',
		infinitive: 'smell',
		pastSimple: 'smelt',
		pastParticiple: 'smelt',
		group: 2,
		type: 1,
	},
	// {
	// 	id: 144,
	// 	rus: 'сеять',
	// 	infinitive: 'sow',
	// 	pastSimple: 'sowed',
	// 	pastParticiple: 'sowed/sown',
	// 	group: 2,
	// 	type: 1,
	// },
	{
		id: 145,
		rus: 'говорить',
		infinitive: 'speak',
		pastSimple: 'spoke',
		pastParticiple: 'spoken',
		group: 1,
		type: 1,
	},
	{
		id: 146,
		rus: 'спешить, ускорять',
		infinitive: 'speed',
		pastSimple: 'sped',
		pastParticiple: 'sped',
		group: 2,
		type: 1,
	},
	{
		id: 147,
		rus: 'писать, произносить слово по буквам',
		infinitive: 'spell',
		pastSimple: 'spelt',
		pastParticiple: 'spelt',
		group: 3,
		type: 1,
	},
	{
		id: 148,
		rus: 'тратить, истощать',
		infinitive: 'spend',
		pastSimple: 'spent',
		pastParticiple: 'spent',
		group: 2,
		type: 1,
	},
	{
		id: 149,
		rus: 'проливать',
		infinitive: 'spill',
		pastSimple: 'spilt',
		pastParticiple: 'spilt',
		group: 3,
		type: 1,
	},
	{
		id: 150,
		rus: 'прясть',
		infinitive: 'spin',
		pastSimple: 'spun',
		pastParticiple: 'spun',
		group: 3,
		type: 1,
	},
	{
		id: 151,
		rus: 'плевать, насаживать, натыкать',
		infinitive: 'spit',
		pastSimple: 'spat',
		pastParticiple: 'spat',
		group: 3,
		type: 1,
	},
	{
		id: 152,
		rus: 'раскалывать, расщеплять',
		infinitive: 'split',
		pastSimple: 'split',
		pastParticiple: 'split',
		group: 3,
		type: 1,
	},
	{
		id: 153,
		rus: 'портить, баловать',
		infinitive: 'spoil',
		pastSimple: 'spoilt',
		pastParticiple: 'spoilt',
		group: 3,
		type: 1,
	},
	{
		id: 154,
		rus: 'распространяться',
		infinitive: 'spread',
		pastSimple: 'spread',
		pastParticiple: 'spread',
		group: 2,
		type: 1,
	},
	{
		id: 155,
		rus: 'прыгать, вскочить',
		infinitive: 'spring',
		pastSimple: 'sprang',
		pastParticiple: 'sprung',
		group: 2,
		type: 1,
	},
	{
		id: 156,
		rus: 'стоять',
		infinitive: 'stand',
		pastSimple: 'stood',
		pastParticiple: 'stood',
		group: 1,
		type: 1,
	},
	{
		id: 157,
		rus: 'воровать, красть',
		infinitive: 'steal',
		pastSimple: 'stole',
		pastParticiple: 'stolen',
		group: 2,
		type: 1,
	},
	{
		id: 158,
		rus: 'втыкать, приклеивать(ся), липнуть',
		infinitive: 'stick',
		pastSimple: 'stuck',
		pastParticiple: 'stuck',
		group: 2,
		type: 1,
	},
	{
		id: 159,
		rus: 'жалить',
		infinitive: 'sting',
		pastSimple: 'stung',
		pastParticiple: 'stung',
		group: 3,
		type: 1,
	},
	{
		id: 160,
		rus: 'вонять, отталкивать',
		infinitive: 'stink',
		pastSimple: 'stank',
		pastParticiple: 'stunk',
		group: 2,
		type: 1,
	},
	{
		id: 161,
		rus: 'усеять, разбрасывать, расстилать',
		infinitive: 'strew',
		pastSimple: 'strewed',
		pastParticiple: 'strewn',
		group: 3,
		type: 1,
	},
	{
		id: 162,
		rus: 'шагать',
		infinitive: 'stride',
		pastSimple: 'strode',
		pastParticiple: 'stridden',
		group: 3,
		type: 1,
	},
	{
		id: 163,
		rus: 'ударять, поражать, бастовать',
		infinitive: 'strike',
		pastSimple: 'struck',
		pastParticiple: 'struck',
		group: 3,
		type: 1,
	},
	{
		id: 164,
		rus: 'связывать, натягивать, нанизывать',
		infinitive: 'string',
		pastSimple: 'strung',
		pastParticiple: 'strung',
		group: 3,
		type: 1,
	},
	{
		id: 165,
		rus: 'стремиться, стараться',
		infinitive: 'strive',
		pastSimple: 'strove',
		pastParticiple: 'striven',
		group: 3,
		type: 1,
	},
	{
		id: 166,
		rus: 'клясться, присягать, браниться',
		infinitive: 'swear',
		pastSimple: 'swore',
		pastParticiple: 'sworn',
		group: 3,
		type: 1,
	},
	{
		id: 167,
		rus: 'мести',
		infinitive: 'sweep',
		pastSimple: 'swept',
		pastParticiple: 'swept',
		group: 3,
		type: 1,
	},
	{
		id: 168,
		rus: 'пухнуть, раздуваться, набухать',
		infinitive: 'swell',
		pastSimple: 'swelled',
		pastParticiple: 'swollen',
		group: 3,
		type: 1,
	},
	{
		id: 169,
		rus: 'плавать',
		infinitive: 'swim',
		pastSimple: 'swam',
		pastParticiple: 'swum',
		group: 1,
		type: 1,
	},
	{
		id: 170,
		rus: 'качать(ся), размахивать',
		infinitive: 'swing',
		pastSimple: 'swung',
		pastParticiple: 'swung',
		group: 3,
		type: 1,
	},
	{
		id: 171,
		rus: 'брать',
		infinitive: 'take',
		pastSimple: 'took',
		pastParticiple: 'taken',
		group: 1,
		type: 1,
	},
	{
		id: 172,
		rus: 'обучать, учить',
		infinitive: 'teach',
		pastSimple: 'taught',
		pastParticiple: 'taught',
		group: 1,
		type: 1,
	},
	{
		id: 173,
		rus: 'рвать',
		infinitive: 'tear',
		pastSimple: 'tore',
		pastParticiple: 'torn',
		group: 3,
		type: 1,
	},
	{
		id: 174,
		rus: 'рассказывать, сообщать',
		infinitive: 'tell',
		pastSimple: 'told',
		pastParticiple: 'told',
		group: 1,
		type: 1,
	},
	{
		id: 175,
		rus: 'думать',
		infinitive: 'think',
		pastSimple: 'thought',
		pastParticiple: 'thought',
		group: 1,
		type: 1,
	},
	{
		id: 176,
		rus: 'кидать, бросать',
		infinitive: 'throw',
		pastSimple: 'threw',
		pastParticiple: 'thrown',
		group: 2,
		type: 1,
	},
	{
		id: 177,
		rus: 'толкать, колоть, выгонять, сунуть',
		infinitive: 'thrust',
		pastSimple: 'thrust',
		pastParticiple: 'thrust',
		group: 3,
		type: 1,
	},
	{
		id: 178,
		rus: 'ступать',
		infinitive: 'tread',
		pastSimple: 'trod',
		pastParticiple: 'trod',
		group: 3,
		type: 1,
	},
	{
		id: 179,
		rus: 'разгибаться',
		infinitive: 'unbend',
		pastSimple: 'unbent',
		pastParticiple: 'unbent',
		group: 3,
		type: 1,
	},
	{
		id: 180,
		rus: 'испытывать, переносить',
		infinitive: 'undergo',
		pastSimple: 'underwent',
		pastParticiple: 'undergone',
		group: 3,
		type: 1,
	},
	{
		id: 181,
		rus: 'понимать',
		infinitive: 'understand',
		pastSimple: 'understood',
		pastParticiple: 'understood',
		group: 1,
		type: 1,
	},
	{
		id: 182,
		rus: 'предпринимать, гарантировать',
		infinitive: 'undertake',
		pastSimple: 'undertook',
		pastParticiple: 'undertaken',
		group: 3,
		type: 1,
	},
	{
		id: 183,
		rus: 'опрокидывать, обжимать',
		infinitive: 'upset',
		pastSimple: 'upset',
		pastParticiple: 'upset',
		group: 3,
		type: 1,
	},
	{
		id: 184,
		rus: 'будить, просыпаться',
		infinitive: 'wake',
		pastSimple: 'woke',
		pastParticiple: 'woken',
		group: 2,
		type: 1,
	},
	{
		id: 185,
		rus: 'носить (одежду)',
		infinitive: 'wear',
		pastSimple: 'wore',
		pastParticiple: 'worn',
		group: 2,
		type: 1,
	},
	{
		id: 186,
		rus: 'ткать',
		infinitive: 'weave',
		pastSimple: 'wove',
		pastParticiple: 'woven',
		group: 3,
		type: 1,
	},
	{
		id: 187,
		rus: 'венчать(ся), выдавать замуж',
		infinitive: 'wed',
		pastSimple: 'wed',
		pastParticiple: 'wed',
		group: 2,
		type: 1,
	},
	{
		id: 188,
		rus: 'плакать',
		infinitive: 'weep',
		pastSimple: 'wept',
		pastParticiple: 'wept',
		group: 2,
		type: 1,
	},
	{
		id: 189,
		rus: 'хотеть быть',
		infinitive: 'will',
		pastSimple: 'would',
		pastParticiple: 'would',
		group: 2,
		type: 1,
	},
	{
		id: 190,
		rus: 'мочить',
		infinitive: 'wet',
		pastSimple: 'wet',
		pastParticiple: 'wet',
		group: 3,
		type: 1,
	},
	{
		id: 191,
		rus: 'выигрывать, получать',
		infinitive: 'win',
		pastSimple: 'won',
		pastParticiple: 'won',
		group: 1,
		type: 1,
	},
	{
		id: 192,
		rus: 'заводить (механизм), виться',
		infinitive: 'wind',
		pastSimple: 'wound',
		pastParticiple: 'wound',
		group: 3,
		type: 1,
	},
	{
		id: 193,
		rus: 'брать назад, отнимать',
		infinitive: 'withdraw',
		pastSimple: 'withdrew',
		pastParticiple: 'withdrawn',
		group: 3,
		type: 1,
	},
	{
		id: 194,
		rus: 'жать (хлеб), выжимать, скручивать',
		infinitive: 'wring',
		pastSimple: 'wrung',
		pastParticiple: 'wrung',
		group: 4,
		type: 1,
	},
	{
		id: 195,
		rus: 'писать',
		infinitive: 'write',
		pastSimple: 'wrote',
		pastParticiple: 'written',
		group: 1,
		type: 1,
	},
];

global.verbsList = verbsList;
global.levels = levels;
global.verbForms = verbForms;
global.phrases = phrases;

export default global;